### ISSUE TITLE
Crash - NSKeyedUnarchiver initForReadingWithData incomprehensible archive

### ISSUE THREAD

**Issue by lukegeiger** [Simperium/simperium-ios#453]
I am testing my app on multiple devices, both are logged into the same account. I did some changes and updates on one and now when I launch the app on the other device I get a crash on launch every time with the following message

    Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSKeyedUnarchiver initForReadingWithData:]: incomprehensible archive (0x3, 0x6d, 0x37, 0xffffffef, 0x5f, 0xffffff87, 0x47, 0xffffff95)'
    *** First throw call stack:

I crash on line 52 of SPMemberBase64 [Here](https://github.com/Simperium/simperium-ios/blob/3195a286985349cd019ca171143adacb02d214df/Simperium/SPMemberBase64.m#L53)

**Comment by jleandroperez** [comment]
@lukegeiger the reason why the app is crashing, is that Simperium normally attempts to merge Strings.
If your strings are base64 encoded, odds are that, at some point, the stored data will break.

The way around this is to setup a Schema, so that whenever this field is updated, a `Replace Operation` is sent to all of the listeners (instead of sending diffs over).

The way to do that is as follows:

```
POST https://api.simperium.com/1/<app id>/__options__/i/<bucket name>
 
{ "schema" : { "attributes" : { "<fieldname>" :{ "otype" : "replace" } } } }
 
 
Example:
 
App ID: test-app-1337
Bucket Name: blarb
Field Name: b64thing
 
POST https://api.simperium.com/1/test-app-1337/__options__/i/blarb
 
{ "schema" : { "attributes" : { "b64thing" :{ "otype" : "replace" } } } }
 
Will change the default diff mode for the field "b64thing" for objects in the "blarb" bucket from string to replace.
```


I've filed issue #456 to update the documentation, reflecting this.

Thank you!

**Comment by lukegeiger** [comment]
@jleandroperez 

Ok, but I don't have any base64 Encoding. I do though have a string property that is XOR'ed but once it is created and saved, I never update it again. Any thoughts on this?

**Comment by jleandroperez** [comment]
@lukegeiger Any *Transformable* attribute is [internally mapped as base64](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPCoreDataExporter.m#L45).

Enabling the Replace OP via schema should fix this issue.

Thank you!

**Comment by lukegeiger** [comment]
@jleandroperez probably a stupid question... But how do I replace OP via schema? Not sure where to change the code you posted in my project.

**Comment by jleandroperez** [comment]
@lukegeiger sorry about the misunderstanding!. This is not something you set in the app itself, but a request you'd need to execute.

There are several tools that can help you out, but you probably already have **curl** installed.

```
POST https://api.simperium.com/1/<app id>/__options__/i/<bucket name>

{ "schema" : { "attributes" : { "<fieldname>" :{ "otype" : "replace" } } } }


Example:

App ID: test-app-1337
Bucket Name: blarb
Field Name: b64thing

POST https://api.simperium.com/1/test-app-1337/__options__/i/blarb

{ "schema" : { "attributes" : { "b64thing" :{ "otype" : "replace" } } } }

Will change the default diff mode for the field "b64thing" for objects in the "blarb" bucket from string to replace.
```

**Comment by lukegeiger** [comment]
@jleandroperez still not quite getting this. So I have to execute this execute this command on every bucket on Simperium that holds a string?

I'd really rather not touch any of my buckets via the command line. Are there any alternatives to taking this approach?

I feel like my use case is a very common one, and I'm sure it has to have come up before. Are there any adjustments to the framework itself that would be able to support a user being logged in on the same account on two devices?

**Comment by jleandroperez** [comment]
@lukegeiger not quite. You'd need to execute this, command line, just once, and *only* for those fields that are stored as *base64* (Transformables).

This is something that affects the app, globally, and it's not required on a per-user basis.

We'll be enhancing the library in the future, so if there are transformables, this is something handled automatically. However, currently, schema settings is the only way around.

Sorry about this inconvenience Luke!

**Comment by lukegeiger** [comment]
@jleandroperez so I have two Transformables in my app on two different buckets (we are talking about this on a separate issue right now). That means I need to execute this twice, once for each bucket?

So each of those commands would look exactly like your command, the only difference is my app ID, my bucket name, and my field name?

I know when I was using the http api before, every time that I did not put all a buckets attributes in a POST command, they would all get removed from the bucket. Can you confirm that I do not need to list out every attribute of the Bucket when I do this? Just the Transformable property?

**Comment by lukegeiger** [comment]
Also, I apologize but can you list out the command *exactly* how it should be pasted into the command line? 

I am trying

    POST https://api.simperium.com/1/myID/__options__/i/myBucket
    { "schema" : { "attributes" : { “myAtt” :{ "otype" : "replace" } } } }

but it does not seem to be working

**Comment by jleandroperez** [comment]
No worries!. This is part of the [HTTP API](https://simperium.com/docs/reference/http/).
Detailed instructions below:

1. Log into Simperium.com, and under `API Keys`, grab your `Admin Key`

2. Open Terminal, and type the following
```
	curl -H 'X-Simperium-API-Key: ADMIN_KEY' \
    	-d '{"username":"YOUR@USERNAME.COM", "password":"PASSWORD"}' \
	    https://auth.simperium.com/1/APP_ID/authorize/
``

3. As a result, you should see something as follows:

	`{"username": "..", "access_token": "..", "userid": ".."}`

4. Jot down the `access_token`, we'll need it!.

5. Type the following command:

```
curl -H 'X-Simperium-Token: ADMIN_ACCESS_TOKEN' https://api.simperium.com/1/APP_ID/__options__/i/BUCKET_NAME -d '{ "schema" : { "attributes" : { "ATTRIBUTE_NAME" :{ "otype" : "replace" } } } }'
```

**Note:** This will set the schema preferences for a given bucket. You should perform one call per bucket, since this call is not additive. Meaning that if you'd require to enable `Replace` for multiple attributes in just one bucket, please, modify the json as required.

6. Validate the settings:

```
curl -H 'X-Simperium-Token: ADMIN_ACCESS_TOKEN' https://api.simperium.com/1/APP_ID/__options__/i/BUCKET_NAME
```

At this point, you should see onscreen a dictionary representing the schema settings for a given bucket. Only the "Transformable" fields should show up.


Thank you!

**Comment by lukegeiger** [comment]
@jleandroperez 

I am trying to get past step two, but not sure what is happening, after typing what you said I get the following response

    curl: (6) Could not resolve host:  -d

    [1/2]: "username”:”MYEMAIL” --> <stdout>
    --_curl_--"username”:”MYEMAIL”
    <html>
    <head><title>301 Moved Permanently</title></head>
    <body bgcolor="white">
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>

    [2/2]:  "password”:”MYPASSWORD” --> <stdout>
    --_curl_-- "password":"MYPASSWORD”
    curl: (6) Could not resolve host:  "password"
    curl: (1) Protocol  https not supported or disabled in libcurl

**Comment by jleandroperez** [comment]
@lukegeiger This is working for me in the command line. Make sure that the username + password you try, is already registered in that Simperium APP. This is an authentication call, not a signup service.

```
 curl -H 'X-Simperium-API-Key: API_KEY' \
    -d '{"username":"EMAIL@DOMAIN.COM", "password":"PASSWORD"}' \
    https://auth.simperium.com/1/APP_ID/authorize/
```

**Example:**

```
API Key: 1111 
App ID: something
Email: you@domain.com
Password = 2222
```

Command:
```
 curl -H 'X-Simperium-API-Key: 1111' \
    -d '{"username":"you@domain.com", "password":"2222"}' \
    https://auth.simperium.com/1/something/authorize/
```

**Comment by lukegeiger** [comment]
@jleandroperez yeah, I'm not sure what I am doing wrong. here is a gist to my [command](https://gist.githubusercontent.com/lukegeiger/6425f6eb02093c47e880/raw/538e7ce1dfbe77b3137c9e94863df4e430f31677/gistfile1.txt)

**Comment by lukegeiger** [comment]
@jleandroperez Yeah not sure what I am doing wrong, I posted the gist to the command I am using on this thread, but it got deleted somehow, let me know if you want me to resend it. (it did not contain any sensitive information, all passwords/emails are for a a test account on simperium.com)

**Comment by jleandroperez** [comment]
@lukegeiger i've deleted the last comment, for safety reasons. (Please: change your password as soon as possible!).

There are three issues in the command you're using:
- There is a typo in your *App ID*, the actual one ends in *1b5*, not `lb5`
- Backslashes are only required if the command spans over multiple lines. You're just typing it all in one line. In that case, please, remove all of the `\` occurrences.
- Apparently, the password you're using is the *Admin* password. Please, use a set of credentials of an actual *User* (not an admin). I.E.: an user of your app, in that environment.

Thanks!

**Comment by lukegeiger** [comment]
@jleandroperez ok thanks I will try it out. Like I said in the previous post, the gist only contained information for a test account on simperium that I only use.

**Comment by jleandroperez** [comment]
@lukegeiger awesome, thank you!

**Comment by lukegeiger** [comment]
@jleandroperez Finally got it. Thanks so much, you saved the day again! I aplogize for being a noob at typing in http commands!

**Comment by jleandroperez** [comment]
No worries at all @lukegeiger!. After setting up the schema setting, whenever any of the devices updates (any of the) the affected fields, the rest of the devices shouldn't get a diff anymore.

(But the whole string again).

If there's anything we could help you with // if you're still having trouble, please, just let us know.

Thanks!

**Comment by lukegeiger** [comment]
Ok great thanks.



—
lg

**Comment by jleandroperez** [comment]
@lukegeiger if you're still experiencing this issue, please, feel free to reopen.

Thank you!
